Fix: build failure due to missing include
The macros are defined in sys/sysmacros.h, it may be implicitly
included in previous version of something else.

The following build error is present on Arch without the patch:

```
quick_search/dquicksearch.cpp: In static member function ‘static bool DQuickSearch::isUsbDevice(const QString&)’:
quick_search/dquicksearch.cpp:1034:52: error: ‘major’ was not declared in this scope
         sprintf(link_path, "/sys/dev/block/%d:%d", major(buf.st_rdev), minor(buf.st_rdev));
                                                    ^~~~~
quick_search/dquicksearch.cpp:1034:72: error: ‘minor’ was not declared in this scope
         sprintf(link_path, "/sys/dev/block/%d:%d", major(buf.st_rdev), minor(buf.st_rdev));
                                                                        ^~~~~
```

Change-Id: I09ea552da9aedda63e5128f18a77bf8414053143